### ISSUE TITLE
Conflicting information given about licensing

### ISSUE THREAD

**Issue by rossmounce** [exciteproject/Exparser#5]
On the project overview page (http://excite.west.uni-koblenz.de/) it is written:

> All tools are licensed under Creative Commons attribution (CC BY-NC) and their codes are available on GitHub

This is not currently true. For instance the LICENSE file of this repository (https://github.com/exciteproject/Exparser/blob/master/LICENSE) for Exparser, indicates that this tool is licensed under the GNU General Public License v3.0.

GNU GPL v3.0 is _not_ CC BY-NC. Please fix.

**Comment by behnam2014** [comment]
The website is corrected and changed to GNU General Public License v3.0
